# Generated by Django 4.2.1 on 2023-05-10 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0004_remove_user_password_user_is_active_user_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
