# Generated by Django 4.2.1 on 2023-05-10 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0005_remove_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tienda.store'),
        ),
    ]
