# Generated by Django 4.2.1 on 2023-05-10 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0006_remove_user_is_admin_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
