# Generated by Django 4.2.1 on 2023-05-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0008_remove_user_favorite_store_alter_user_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='email',
        ),
    ]
